# Generated by Django 2.0.1 on 2018-03-15 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.IntegerField(db_column='ISBN', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Book Name', max_length=30)),
                ('author', models.CharField(db_column='Author Name', max_length=20)),
                ('date_issued', models.DateField(db_column='Date of Issue')),
                ('date_of_return', models.DateField(db_column='Date of Return')),
                ('freq', models.IntegerField()),
            ],
            options={
                'ordering': ['date_of_return'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
