# Generated by Django 2.0.1 on 2018-03-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180320_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.AddField(
            model_name='book',
            name='freq',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
