# Generated by Django 2.0.2 on 2018-03-30 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_noofsubjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1', models.CharField(max_length=30)),
                ('sub2', models.CharField(blank=True, max_length=30, null=True)),
                ('sub3', models.CharField(blank=True, max_length=30, null=True)),
                ('sub4', models.CharField(blank=True, max_length=30, null=True)),
                ('sub5', models.CharField(blank=True, max_length=30, null=True)),
                ('sub6', models.CharField(blank=True, max_length=30, null=True)),
                ('sub7', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
