# Generated by Django 2.0.2 on 2018-03-30 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Monday_Hour1', models.CharField(blank=True, max_length=30, null=True)),
                ('Monday_Hour2', models.CharField(blank=True, max_length=30, null=True)),
                ('Monday_Hour3', models.CharField(blank=True, max_length=30, null=True)),
                ('Monday_Hour4', models.CharField(blank=True, max_length=30, null=True)),
                ('Monday_Hour5', models.CharField(blank=True, max_length=30, null=True)),
                ('Monday_Hour6', models.CharField(blank=True, max_length=30, null=True)),
                ('Monday_Hour7', models.CharField(blank=True, max_length=30, null=True)),
                ('Monday_Hour8', models.CharField(blank=True, max_length=30, null=True)),
                ('Tuesday_Hour1', models.CharField(blank=True, max_length=30, null=True)),
                ('Tuesday_Hour2', models.CharField(blank=True, max_length=30, null=True)),
                ('Tuesday_Hour3', models.CharField(blank=True, max_length=30, null=True)),
                ('Tuesday_Hour4', models.CharField(blank=True, max_length=30, null=True)),
                ('Tuesday_Hour5', models.CharField(blank=True, max_length=30, null=True)),
                ('Tuesday_Hour6', models.CharField(blank=True, max_length=30, null=True)),
                ('Tuesday_Hour7', models.CharField(blank=True, max_length=30, null=True)),
                ('Tuesday_Hour8', models.CharField(blank=True, max_length=30, null=True)),
                ('Wednesday_Hour1', models.CharField(blank=True, max_length=30, null=True)),
                ('Wednesday_Hour2', models.CharField(blank=True, max_length=30, null=True)),
                ('Wednesday_Hour3', models.CharField(blank=True, max_length=30, null=True)),
                ('Wednesday_Hour4', models.CharField(blank=True, max_length=30, null=True)),
                ('Wednesday_Hour5', models.CharField(blank=True, max_length=30, null=True)),
                ('Wednesday_Hour6', models.CharField(blank=True, max_length=30, null=True)),
                ('Wednesday_Hour7', models.CharField(blank=True, max_length=30, null=True)),
                ('Wednesday_Hour8', models.CharField(blank=True, max_length=30, null=True)),
                ('Thursday_Hour1', models.CharField(blank=True, max_length=30, null=True)),
                ('Thursday_Hour2', models.CharField(blank=True, max_length=30, null=True)),
                ('Thursday_Hour3', models.CharField(blank=True, max_length=30, null=True)),
                ('Thursday_Hour4', models.CharField(blank=True, max_length=30, null=True)),
                ('Thursday_Hour5', models.CharField(blank=True, max_length=30, null=True)),
                ('Thursday_Hour6', models.CharField(blank=True, max_length=30, null=True)),
                ('Thursday_Hour7', models.CharField(blank=True, max_length=30, null=True)),
                ('Thursday_Hour8', models.CharField(blank=True, max_length=30, null=True)),
                ('Friday_Hour1', models.CharField(blank=True, max_length=30, null=True)),
                ('Friday_Hour2', models.CharField(blank=True, max_length=30, null=True)),
                ('Friday_Hour3', models.CharField(blank=True, max_length=30, null=True)),
                ('Friday_Hour4', models.CharField(blank=True, max_length=30, null=True)),
                ('Friday_Hour5', models.CharField(blank=True, max_length=30, null=True)),
                ('Friday_Hour6', models.CharField(blank=True, max_length=30, null=True)),
                ('Friday_Hour7', models.CharField(blank=True, max_length=30, null=True)),
                ('Friday_Hour8', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
