# Generated by Django 2.0.1 on 2018-04-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='Friday_Hour1',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Friday_Hour2',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Friday_Hour3',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Friday_Hour4',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Friday_Hour5',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Friday_Hour6',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Friday_Hour7',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Friday_Hour8',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Monday_Hour1',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Monday_Hour2',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Monday_Hour3',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Monday_Hour4',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Monday_Hour5',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Monday_Hour6',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Monday_Hour7',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Monday_Hour8',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Thursday_Hour1',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Thursday_Hour2',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Thursday_Hour3',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Thursday_Hour4',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Thursday_Hour5',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Thursday_Hour6',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Thursday_Hour7',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Thursday_Hour8',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Tuesday_Hour1',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Tuesday_Hour2',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Tuesday_Hour3',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Tuesday_Hour4',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Tuesday_Hour5',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Tuesday_Hour6',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Tuesday_Hour7',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Tuesday_Hour8',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Wednesday_Hour1',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Wednesday_Hour2',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Wednesday_Hour3',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Wednesday_Hour4',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Wednesday_Hour5',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Wednesday_Hour6',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Wednesday_Hour7',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Wednesday_Hour8',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
    ]
