# Generated by Django 2.0.1 on 2018-03-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_clothes_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='category',
            field=models.CharField(choices=[('FORMAL', 'Formal Wear'), ('CASUAL', 'Casual Wear'), ('SEMI-FORMAL', 'Semi-Formal Wear'), ('NIGHT-WEAR', 'Night Wear')], db_column='Category', max_length=10),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='colour',
            field=models.CharField(choices=[('White', 'White'), ('Red', 'Red'), ('Black', 'Black'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Green', 'Green'), ('Grey', 'Grey'), ('Pink', 'Pink'), ('Other', 'Other')], db_column='Colour', max_length=10),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='types',
            field=models.CharField(choices=[('TEEs', 'Tee(s)'), ('PANTS', 'Pants'), ('JEANS', 'Jeans'), ('SHIRT', 'Shirt(s)'), ('SHORTS', 'Shorts)'), ('UNDERGARMENTS', 'Undergarment(s)'), ('SOCKS', 'Socks'), ('ETHNIC TOP', 'Ethnic Top(s)'), ('ETHNIC BOTTOM', 'Ethnic Bottom(s)'), ('TOP', "Women's Top(s)"), ('SKIRT', 'Skirt(s)'), ('LEGGINGS', 'Leggings/Skins'), ('DRESS', "Women's Dress(es)")], db_column='Type', max_length=10),
        ),
    ]
