# Generated by Django 2.0.1 on 2018-03-13 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20180313_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='uid',
        ),
    ]
