# Generated by Django 2.0.1 on 2018-03-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20180313_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='tag',
            field=models.TextField(max_length=20),
        ),
    ]
