# Generated by Django 2.0.1 on 2018-03-20 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0005_auto_20180320_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(db_column='Name', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('details', models.TextField()),
                ('happy', models.BooleanField()),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='types',
            field=models.CharField(choices=[('Tee(s)', 'Tee(s)'), ('Pant(s)', 'Pants'), ('Jeans', 'Jeans'), ('Shirt(s)', 'Shirt(s)'), ('Shorts', 'Shorts'), ('Undergarment(s)', 'Undergarment(s)'), ('Socks', 'Socks'), ('Ethnic Top(s)', 'Ethnic Top(s)'), ('Ethnic Bottom(s)', 'Ethnic Bottom(s)'), ('Top(s)', "Women's Top(s)"), ('Skirt(s)', 'Skirt(s)'), ('Leggings', 'Leggings/Skins'), ('Dress(es)', "Women's Dress(es)")], db_column='Type', max_length=20),
        ),
    ]
