# Generated by Django 2.0.3 on 2018-03-26 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20180320_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fitness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('category', models.CharField(choices=[('Run', 'Run'), ('Cycle ride', 'Cycle ride'), ('Basketball', 'Basketball'), ('Yoga', 'Yoga'), ('Tennis', 'Tennis'), ('Football', 'Football'), ('Cricket', 'Cricket'), ('Badminton', 'Badminton'), ('CrossFit', 'CrossFit'), ('Weight Lifting', 'Weight Lifting')], db_column='Category', max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
