# Generated by Django 2.0.3 on 2018-03-26 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20180326_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitness',
            name='weight',
        ),
    ]
