# Generated by Django 2.0.1 on 2018-03-27 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_fitness_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitness',
            name='user',
        ),
        migrations.DeleteModel(
            name='Fitness',
        ),
    ]
