# Generated by Django 2.0.1 on 2018-03-27 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0011_auto_20180327_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fitness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('calories', models.FloatField()),
                ('category', models.CharField(choices=[('Run', 'Run'), ('Cycle ride', 'Cycle ride'), ('Basketball', 'Basketball'), ('Yoga', 'Yoga'), ('Tennis', 'Tennis'), ('Football', 'Football'), ('Cricket', 'Cricket'), ('Badminton', 'Badminton'), ('CrossFit', 'CrossFit'), ('Weight Lifting', 'Weight Lifting'), ('Jump Rope', 'Jump Rope'), ('Swimming', 'Swimming')], db_column='Category', max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
