# Generated by Django 2.0.1 on 2018-03-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_fitness'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitness',
            name='weight',
            field=models.FloatField(default=60),
            preserve_default=False,
        ),
    ]
