# Generated by Django 2.0.1 on 2018-03-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_fitness_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitness',
            name='category',
            field=models.CharField(choices=[('Run', 'Run'), ('Cycle Ride', 'Cycle Ride'), ('Basketball', 'Basketball'), ('Yoga', 'Yoga'), ('Tennis', 'Tennis'), ('Football', 'Football'), ('Cricket', 'Cricket'), ('Badminton', 'Badminton'), ('CrossFit', 'CrossFit'), ('Weight Lifting', 'Weight Lifting'), ('Jump Rope', 'Jump Rope'), ('Swimming', 'Swimming')], db_column='Category', max_length=20),
        ),
    ]
