# Generated by Django 2.0.2 on 2018-03-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_auto_20180305_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='published_date',
            new_name='due_date',
        ),
    ]
